-- 00: account objects. Run as ACCOUNTADMIN.
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS ONTOFLAKE COMMENT = 'OntoFlake - governed supply chain ontology';
CREATE SCHEMA IF NOT EXISTS ONTOFLAKE.RAW       COMMENT = 'Landed source extracts (ERP, WMS, TMS, supplier portal)';
CREATE SCHEMA IF NOT EXISTS ONTOFLAKE.CONFORMED COMMENT = 'Ontology-shaped dimensions and facts';
CREATE SCHEMA IF NOT EXISTS ONTOFLAKE.SEMANTIC  COMMENT = 'Semantic views = the governed ontology';
CREATE SCHEMA IF NOT EXISTS ONTOFLAKE.GOV       COMMENT = 'Roles, policies, persona scope maps';

CREATE STAGE IF NOT EXISTS ONTOFLAKE.RAW.LANDING FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' NULL_IF = ('', 'None'));
