-- 02: load CSVs from stage into RAW. Files are PUT by scripts/deploy.ps1.
USE SCHEMA ONTOFLAKE.RAW;

TRUNCATE TABLE IF EXISTS SUPPLIER; TRUNCATE TABLE IF EXISTS PART; TRUNCATE TABLE IF EXISTS PLANT; TRUNCATE TABLE IF EXISTS CUSTOMER; TRUNCATE TABLE IF EXISTS CARRIER;
TRUNCATE TABLE IF EXISTS SOURCE_LIST; TRUNCATE TABLE IF EXISTS PURCHASE_ORDER_LINE; TRUNCATE TABLE IF EXISTS INBOUND_SHIPMENT; TRUNCATE TABLE IF EXISTS SALES_ORDER_LINE; TRUNCATE TABLE IF EXISTS INVENTORY_POSITION;

COPY INTO SUPPLIER            FROM @LANDING/supplier.csv            FORCE = TRUE;
COPY INTO PART                FROM @LANDING/part.csv                FORCE = TRUE;
COPY INTO PLANT               FROM @LANDING/plant.csv               FORCE = TRUE;
COPY INTO CUSTOMER            FROM @LANDING/customer.csv            FORCE = TRUE;
COPY INTO CARRIER             FROM @LANDING/carrier.csv             FORCE = TRUE;
COPY INTO SOURCE_LIST         FROM @LANDING/source_list.csv         FORCE = TRUE;
COPY INTO PURCHASE_ORDER_LINE FROM @LANDING/purchase_order_line.csv FORCE = TRUE;
COPY INTO INBOUND_SHIPMENT    FROM @LANDING/inbound_shipment.csv    FORCE = TRUE;
COPY INTO SALES_ORDER_LINE    FROM @LANDING/sales_order_line.csv    FORCE = TRUE;
COPY INTO INVENTORY_POSITION  FROM @LANDING/inventory_position.csv  FORCE = TRUE;

SELECT 'SUPPLIER' t, COUNT(*) n FROM SUPPLIER
UNION ALL SELECT 'PART', COUNT(*) FROM PART
UNION ALL SELECT 'PLANT', COUNT(*) FROM PLANT
UNION ALL SELECT 'CUSTOMER', COUNT(*) FROM CUSTOMER
UNION ALL SELECT 'CARRIER', COUNT(*) FROM CARRIER
UNION ALL SELECT 'SOURCE_LIST', COUNT(*) FROM SOURCE_LIST
UNION ALL SELECT 'PURCHASE_ORDER_LINE', COUNT(*) FROM PURCHASE_ORDER_LINE
UNION ALL SELECT 'INBOUND_SHIPMENT', COUNT(*) FROM INBOUND_SHIPMENT
UNION ALL SELECT 'SALES_ORDER_LINE', COUNT(*) FROM SALES_ORDER_LINE
UNION ALL SELECT 'INVENTORY_POSITION', COUNT(*) FROM INVENTORY_POSITION;
