-- 05: governance. Personas are roles; scope is data-driven (GOV.PERSONA_SCOPE); policies attach to conformed
-- facts so the semantic view inherits them. Definitions never change per persona - only visibility does.
USE SCHEMA ONTOFLAKE.GOV;

-- Persona roles
CREATE ROLE IF NOT EXISTS SC_PLANNING       COMMENT = 'Supply planning persona - global scope';
CREATE ROLE IF NOT EXISTS SC_PROCUREMENT    COMMENT = 'Procurement / sourcing persona - global scope';
CREATE ROLE IF NOT EXISTS SC_LOGISTICS      COMMENT = 'Logistics persona - global scope, no cost visibility';
CREATE ROLE IF NOT EXISTS SC_LOGISTICS_APAC COMMENT = 'Logistics persona - APAC plants only, no cost visibility';

GRANT ROLE SC_PLANNING, SC_PROCUREMENT, SC_LOGISTICS, SC_LOGISTICS_APAC TO ROLE SYSADMIN;
SET deploying_user = CURRENT_USER();
GRANT ROLE SC_PLANNING, SC_PROCUREMENT, SC_LOGISTICS, SC_LOGISTICS_APAC TO USER IDENTIFIER($deploying_user);

-- Region scope map. A role with no rows here is GLOBAL.
CREATE OR REPLACE TABLE PERSONA_SCOPE (role_name STRING, plant_region STRING);
INSERT INTO PERSONA_SCOPE VALUES ('SC_LOGISTICS_APAC', 'APAC');

-- Row access: global roles see everything; scoped roles see only mapped regions.
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE DROP ALL ROW ACCESS POLICIES;
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_INBOUND_SHIPMENT    DROP ALL ROW ACCESS POLICIES;
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_SALES_ORDER_LINE    DROP ALL ROW ACCESS POLICIES;
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_INVENTORY_POSITION  DROP ALL ROW ACCESS POLICIES;

CREATE OR REPLACE ROW ACCESS POLICY PLANT_REGION_RAP AS (region STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN')
  OR NOT EXISTS (SELECT 1 FROM ONTOFLAKE.GOV.PERSONA_SCOPE s WHERE s.role_name = CURRENT_ROLE())
  OR EXISTS (SELECT 1 FROM ONTOFLAKE.GOV.PERSONA_SCOPE s WHERE s.role_name = CURRENT_ROLE() AND s.plant_region = region);

ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE ADD ROW ACCESS POLICY PLANT_REGION_RAP ON (plant_region);
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_INBOUND_SHIPMENT    ADD ROW ACCESS POLICY PLANT_REGION_RAP ON (plant_region);
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_SALES_ORDER_LINE    ADD ROW ACCESS POLICY PLANT_REGION_RAP ON (plant_region);
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_INVENTORY_POSITION  ADD ROW ACCESS POLICY PLANT_REGION_RAP ON (plant_region);

-- Column masking: logistics personas are not entitled to purchase prices. They get NULL, never a different number.
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE MODIFY COLUMN unit_price           UNSET MASKING POLICY;
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE MODIFY COLUMN price_variance_value UNSET MASKING POLICY;
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE MODIFY COLUMN po_line_value        UNSET MASKING POLICY;

CREATE OR REPLACE MASKING POLICY COST_MASK AS (val NUMBER) RETURNS NUMBER ->
  IFF(CURRENT_ROLE() LIKE 'SC_LOGISTICS%', NULL, val);

ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE MODIFY COLUMN unit_price           SET MASKING POLICY COST_MASK;
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE MODIFY COLUMN price_variance_value SET MASKING POLICY COST_MASK;
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE MODIFY COLUMN po_line_value        SET MASKING POLICY COST_MASK;

-- Object tags for discoverability / lineage
CREATE TAG IF NOT EXISTS ONTOFLAKE.GOV.METRIC_OWNER;
CREATE TAG IF NOT EXISTS ONTOFLAKE.GOV.DATA_DOMAIN;
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_INBOUND_SHIPMENT    SET TAG ONTOFLAKE.GOV.METRIC_OWNER = 'procurement', ONTOFLAKE.GOV.DATA_DOMAIN = 'inbound_logistics';
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_PURCHASE_ORDER_LINE SET TAG ONTOFLAKE.GOV.METRIC_OWNER = 'procurement', ONTOFLAKE.GOV.DATA_DOMAIN = 'procurement';
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_SALES_ORDER_LINE    SET TAG ONTOFLAKE.GOV.METRIC_OWNER = 'logistics',   ONTOFLAKE.GOV.DATA_DOMAIN = 'order_fulfilment';
ALTER TABLE ONTOFLAKE.CONFORMED.FACT_INVENTORY_POSITION  SET TAG ONTOFLAKE.GOV.METRIC_OWNER = 'planning',    ONTOFLAKE.GOV.DATA_DOMAIN = 'inventory';

-- Grants: personas get the semantic view + underlying conformed objects (needed for SEMANTIC_VIEW() expansion), nothing in RAW.
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_PLANNING;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_PROCUREMENT;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_LOGISTICS;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_LOGISTICS_APAC;
GRANT USAGE ON DATABASE ONTOFLAKE TO ROLE SC_PLANNING;
GRANT USAGE ON DATABASE ONTOFLAKE TO ROLE SC_PROCUREMENT;
GRANT USAGE ON DATABASE ONTOFLAKE TO ROLE SC_LOGISTICS;
GRANT USAGE ON DATABASE ONTOFLAKE TO ROLE SC_LOGISTICS_APAC;
GRANT USAGE ON SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_PLANNING;
GRANT USAGE ON SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_PROCUREMENT;
GRANT USAGE ON SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_LOGISTICS;
GRANT USAGE ON SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_LOGISTICS_APAC;
GRANT USAGE ON SCHEMA ONTOFLAKE.SEMANTIC TO ROLE SC_PLANNING;
GRANT USAGE ON SCHEMA ONTOFLAKE.SEMANTIC TO ROLE SC_PROCUREMENT;
GRANT USAGE ON SCHEMA ONTOFLAKE.SEMANTIC TO ROLE SC_LOGISTICS;
GRANT USAGE ON SCHEMA ONTOFLAKE.SEMANTIC TO ROLE SC_LOGISTICS_APAC;
GRANT SELECT ON ALL TABLES IN SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_PLANNING;
GRANT SELECT ON ALL TABLES IN SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_PROCUREMENT;
GRANT SELECT ON ALL TABLES IN SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_LOGISTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_LOGISTICS_APAC;
GRANT SELECT ON SEMANTIC VIEW ONTOFLAKE.SEMANTIC.SUPPLY_CHAIN TO ROLE SC_PLANNING;
GRANT SELECT ON SEMANTIC VIEW ONTOFLAKE.SEMANTIC.SUPPLY_CHAIN TO ROLE SC_PROCUREMENT;
GRANT SELECT ON SEMANTIC VIEW ONTOFLAKE.SEMANTIC.SUPPLY_CHAIN TO ROLE SC_LOGISTICS;
GRANT SELECT ON SEMANTIC VIEW ONTOFLAKE.SEMANTIC.SUPPLY_CHAIN TO ROLE SC_LOGISTICS_APAC;
