-- 06: read-only identity for the public Streamlit Community Cloud app. Key-pair auth only; no password.
-- Public key is injected by scripts/deploy.ps1 from config/keys/ontoflake_app_svc.pub (<% pub_key %>).
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SC_APP_VIEWER COMMENT = 'Read-only viewer for the public OntoFlake app (global scope, sees costs)';
GRANT ROLE SC_APP_VIEWER TO ROLE SYSADMIN;

CREATE USER IF NOT EXISTS ONTOFLAKE_APP_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = SC_APP_VIEWER
  DEFAULT_WAREHOUSE = COMPUTE_WH
  COMMENT = 'Service user for Streamlit Community Cloud deployment of OntoFlake';
ALTER USER ONTOFLAKE_APP_SVC SET RSA_PUBLIC_KEY = '<% pub_key %>';
GRANT ROLE SC_APP_VIEWER TO USER ONTOFLAKE_APP_SVC;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SC_APP_VIEWER;
GRANT USAGE ON DATABASE ONTOFLAKE TO ROLE SC_APP_VIEWER;
GRANT USAGE ON SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_APP_VIEWER;
GRANT USAGE ON SCHEMA ONTOFLAKE.SEMANTIC  TO ROLE SC_APP_VIEWER;
GRANT USAGE ON SCHEMA ONTOFLAKE.GOV       TO ROLE SC_APP_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA ONTOFLAKE.CONFORMED TO ROLE SC_APP_VIEWER;
GRANT SELECT ON SEMANTIC VIEW ONTOFLAKE.SEMANTIC.SUPPLY_CHAIN TO ROLE SC_APP_VIEWER;
GRANT SELECT ON TABLE ONTOFLAKE.GOV.CONSISTENCY_RUN TO ROLE SC_APP_VIEWER;
GRANT SELECT ON TABLE ONTOFLAKE.GOV.PERSONA_SCOPE   TO ROLE SC_APP_VIEWER;

DESCRIBE USER ONTOFLAKE_APP_SVC;
